
import { createClient } from '@supabase/supabase-js';
import { AttendanceRecord, Student, Status, User } from '../types';

// Configuration provided by user
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_KEY || '';

// Initialize Client
export const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

// --- SQL SETUP HELP ---
export const SETUP_SQL = `
-- ⬇️ COPY AND RUN THIS IN SUPABASE SQL EDITOR ⬇️ --

-- 1. Create Students Table
create table if not exists public.students (
  student_id text primary key,
  name text not null,
  class_name text,
  photo_url text
);

-- 2. Create Attendance Logs Table
create table if not exists public.attendance_logs (
  id bigint generated by default as identity primary key,
  student_id text,
  student_name text,
  timestamp text,
  date text,
  status text,
  confidence float8
);

-- 3. Enable Security (Row Level Security)
alter table public.students enable row level security;
alter table public.attendance_logs enable row level security;

-- 4. Create Access Policies (Open for Demo)
-- Note: In production, restricting these is recommended.
create policy "Enable all access for students" on public.students for all using (true);
create policy "Enable all access for attendance" on public.attendance_logs for all using (true);

-- ⬇️ END SQL ⬇️ --
`;

const handleSupabaseError = (error: any, context: string) => {
  // Filter out 42P01 (undefined_table) as we handle it via checkDatabaseConnection
  if (error.code === '42P01' || error.message?.includes('Could not find the table')) {
    console.warn(`⚠️ DB Table missing in [${context}]. Waiting for setup.`);
    return;
  }
  console.error(`❌ Supabase Error [${context}]:`, error.message);
};

/**
 * Checks if the required tables exist.
 */
export const checkDatabaseConnection = async (): Promise<{ connected: boolean; missingTables: boolean }> => {
  try {
    // Try to select 1 record from students to check if table exists
    const { error } = await supabase.from('students').select('student_id').limit(1);

    if (error) {
      if (error.code === '42P01' || error.message?.includes('Could not find the table')) {
        return { connected: true, missingTables: true };
      }
      return { connected: false, missingTables: false };
    }

    return { connected: true, missingTables: false };
  } catch (e) {
    return { connected: false, missingTables: false };
  }
};

/**
 * Verifies a Student ID exists in the database for login.
 */
export const loginStudent = async (studentId: string): Promise<User | null> => {
  try {
    const { data, error } = await supabase
      .from('students')
      .select('*')
      .eq('student_id', studentId)
      .single();

    if (error) {
      if (error.code !== 'PGRST116') { // Ignore "no rows found" error
        handleSupabaseError(error, 'loginStudent');
      }
      return null;
    }

    return {
      id: data.student_id,
      name: data.name,
      role: 'student',
      photoUrl: data.photo_url,
      className: data.class_name
    };
  } catch (err) {
    console.error('Login Network Error:', err);
    return null;
  }
};

/**
 * Uploads a single attendance record to the 'attendance_logs' table.
 */
export const syncAttendanceToCloud = async (record: AttendanceRecord): Promise<boolean> => {
  try {
    const { error } = await supabase
      .from('attendance_logs')
      .insert([
        {
          student_id: record.studentId,
          student_name: record.studentName,
          timestamp: record.timestamp,
          date: record.date,
          status: record.status,
          confidence: record.confidence
        }
      ]);

    if (error) {
      handleSupabaseError(error, 'syncAttendanceToCloud');
      return false;
    }
    console.log('☁️ [Supabase] Record synced successfully:', record.id);
    return true;
  } catch (err) {
    console.error('Supabase Network Error:', err);
    return false;
  }
};

/**
 * Registers a new student in the 'students' table.
 */
export const registerStudentToCloud = async (student: Student): Promise<boolean> => {
  try {
    console.log("☁️ [Supabase] Registering:", student.id);

    const { data, error } = await supabase
      .from('students')
      .insert([
        {
          student_id: student.id,
          name: student.name,
          class_name: student.className,
          photo_url: student.photoUrl
        }
      ])
      .select();

    if (error) {
      handleSupabaseError(error, 'registerStudentToCloud');
      return false;
    }
    console.log('✅ [Supabase] Student registered:', student.id);
    return true;
  } catch (err) {
    console.error('Supabase Network Error:', err);
    return false;
  }
};

/**
 * Fetches all registered students to populate the local state for recognition.
 */
export const fetchStudents = async (): Promise<Student[]> => {
  try {
    const { data, error } = await supabase
      .from('students')
      .select('*');

    if (error) {
      handleSupabaseError(error, 'fetchStudents');
      return [];
    }

    return (data || []).map((s: any) => ({
      id: s.student_id,
      name: s.name,
      className: s.class_name,
      photoUrl: s.photo_url || 'https://picsum.photos/200'
    }));
  } catch (err) {
    console.error('Error fetching students:', err);
    return [];
  }
};

/**
 * Fetches recent attendance logs for the dashboard.
 */
export const fetchAttendanceLogs = async (): Promise<AttendanceRecord[]> => {
  try {
    const { data, error } = await supabase
      .from('attendance_logs')
      .select('*')
      .order('timestamp', { ascending: false })
      .limit(200);

    if (error) {
      handleSupabaseError(error, 'fetchAttendanceLogs');
      return [];
    }

    return (data || []).map((r: any) => ({
      id: r.id?.toString() || crypto.randomUUID(),
      studentId: r.student_id,
      studentName: r.student_name,
      timestamp: r.timestamp,
      date: r.date,
      status: r.status as Status,
      confidence: r.confidence
    }));
  } catch (err) {
    console.error('Error fetching logs:', err);
    return [];
  }
};
